
// This file has been generated by the GUI designer. Do not modify.
namespace bfbbtracker
{
	public partial class Icon
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.Image image;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bfbbtracker.Icon
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 64;
			this.HeightRequest = 64;
			this.Name = "bfbbtracker.Icon";
			// Container child bfbbtracker.Icon.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.image = new global::Gtk.Image();
			this.image.Name = "image";
			this.eventbox.Add(this.image);
			this.Add(this.eventbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.eventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnEventboxButtonPressEvent);
		}
	}
}
