
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label5;

	private global::Gtk.HBox hbox3;

	private global::bfbbtracker.Icon icon1;

	private global::bfbbtracker.Icon icon2;

	private global::bfbbtracker.Icon icon3;

	private global::bfbbtracker.Icon icon4;

	private global::bfbbtracker.Icon icon5;

	private global::bfbbtracker.Icon icon6;

	private global::bfbbtracker.Icon icon7;

	private global::bfbbtracker.Icon icon8;

	private global::bfbbtracker.Icon icon9;

	private global::Gtk.HBox hbox4;

	private global::bfbbtracker.Icon icon10;

	private global::bfbbtracker.Icon icon11;

	private global::bfbbtracker.Icon icon12;

	private global::bfbbtracker.Icon icon13;

	private global::bfbbtracker.Icon icon14;

	private global::bfbbtracker.Icon icon15;

	private global::bfbbtracker.Icon icon16;

	private global::bfbbtracker.Icon icon17;

	private global::bfbbtracker.Icon icon18;

	private global::Gtk.Label label6;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("BFBB Tracker");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(10));
		// Container child vbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Runner 1");
		this.vbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon1 = new global::bfbbtracker.Icon();
		this.icon1.WidthRequest = 64;
		this.icon1.HeightRequest = 64;
		this.icon1.Events = ((global::Gdk.EventMask)(256));
		this.icon1.Name = "icon1";
		this.icon1.image_name = "JF";
		this.hbox3.Add(this.icon1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon2 = new global::bfbbtracker.Icon();
		this.icon2.WidthRequest = 64;
		this.icon2.HeightRequest = 64;
		this.icon2.Events = ((global::Gdk.EventMask)(256));
		this.icon2.Name = "icon2";
		this.icon2.image_name = "DT";
		this.hbox3.Add(this.icon2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon3 = new global::bfbbtracker.Icon();
		this.icon3.WidthRequest = 64;
		this.icon3.HeightRequest = 64;
		this.icon3.Events = ((global::Gdk.EventMask)(256));
		this.icon3.Name = "icon3";
		this.icon3.image_name = "GL";
		this.hbox3.Add(this.icon3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon4 = new global::bfbbtracker.Icon();
		this.icon4.WidthRequest = 64;
		this.icon4.HeightRequest = 64;
		this.icon4.Events = ((global::Gdk.EventMask)(256));
		this.icon4.Name = "icon4";
		this.icon4.image_name = "RB";
		this.hbox3.Add(this.icon4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon4]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon5 = new global::bfbbtracker.Icon();
		this.icon5.WidthRequest = 64;
		this.icon5.HeightRequest = 64;
		this.icon5.Events = ((global::Gdk.EventMask)(256));
		this.icon5.Name = "icon5";
		this.icon5.image_name = "BRC";
		this.hbox3.Add(this.icon5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon5]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon6 = new global::bfbbtracker.Icon();
		this.icon6.WidthRequest = 64;
		this.icon6.HeightRequest = 64;
		this.icon6.Events = ((global::Gdk.EventMask)(256));
		this.icon6.Name = "icon6";
		this.icon6.image_name = "SM";
		this.hbox3.Add(this.icon6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon6]));
		w7.Position = 5;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon7 = new global::bfbbtracker.Icon();
		this.icon7.WidthRequest = 64;
		this.icon7.HeightRequest = 64;
		this.icon7.Events = ((global::Gdk.EventMask)(256));
		this.icon7.Name = "icon7";
		this.icon7.image_name = "KF";
		this.hbox3.Add(this.icon7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon7]));
		w8.Position = 6;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon8 = new global::bfbbtracker.Icon();
		this.icon8.WidthRequest = 64;
		this.icon8.HeightRequest = 64;
		this.icon8.Events = ((global::Gdk.EventMask)(256));
		this.icon8.Name = "icon8";
		this.icon8.image_name = "FDG";
		this.hbox3.Add(this.icon8);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon8]));
		w9.Position = 7;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.icon9 = new global::bfbbtracker.Icon();
		this.icon9.WidthRequest = 64;
		this.icon9.HeightRequest = 64;
		this.icon9.Events = ((global::Gdk.EventMask)(256));
		this.icon9.Name = "icon9";
		this.icon9.image_name = "SBD";
		this.hbox3.Add(this.icon9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.icon9]));
		w10.Position = 8;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Homogeneous = true;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon10 = new global::bfbbtracker.Icon();
		this.icon10.WidthRequest = 64;
		this.icon10.HeightRequest = 64;
		this.icon10.Events = ((global::Gdk.EventMask)(256));
		this.icon10.Name = "icon10";
		this.icon10.image_name = "JF";
		this.hbox4.Add(this.icon10);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon10]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon11 = new global::bfbbtracker.Icon();
		this.icon11.WidthRequest = 64;
		this.icon11.HeightRequest = 64;
		this.icon11.Events = ((global::Gdk.EventMask)(256));
		this.icon11.Name = "icon11";
		this.icon11.image_name = "DT";
		this.hbox4.Add(this.icon11);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon11]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon12 = new global::bfbbtracker.Icon();
		this.icon12.WidthRequest = 64;
		this.icon12.HeightRequest = 64;
		this.icon12.Events = ((global::Gdk.EventMask)(256));
		this.icon12.Name = "icon12";
		this.icon12.image_name = "GL";
		this.hbox4.Add(this.icon12);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon12]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon13 = new global::bfbbtracker.Icon();
		this.icon13.WidthRequest = 64;
		this.icon13.HeightRequest = 64;
		this.icon13.Events = ((global::Gdk.EventMask)(256));
		this.icon13.Name = "icon13";
		this.icon13.image_name = "RB";
		this.hbox4.Add(this.icon13);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon13]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon14 = new global::bfbbtracker.Icon();
		this.icon14.WidthRequest = 64;
		this.icon14.HeightRequest = 64;
		this.icon14.Events = ((global::Gdk.EventMask)(256));
		this.icon14.Name = "icon14";
		this.icon14.image_name = "BRC";
		this.hbox4.Add(this.icon14);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon14]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon15 = new global::bfbbtracker.Icon();
		this.icon15.WidthRequest = 64;
		this.icon15.HeightRequest = 64;
		this.icon15.Events = ((global::Gdk.EventMask)(256));
		this.icon15.Name = "icon15";
		this.icon15.image_name = "SM";
		this.hbox4.Add(this.icon15);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon15]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon16 = new global::bfbbtracker.Icon();
		this.icon16.WidthRequest = 64;
		this.icon16.HeightRequest = 64;
		this.icon16.Events = ((global::Gdk.EventMask)(256));
		this.icon16.Name = "icon16";
		this.icon16.image_name = "KF";
		this.hbox4.Add(this.icon16);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon16]));
		w18.Position = 6;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon17 = new global::bfbbtracker.Icon();
		this.icon17.WidthRequest = 64;
		this.icon17.HeightRequest = 64;
		this.icon17.Events = ((global::Gdk.EventMask)(256));
		this.icon17.Name = "icon17";
		this.icon17.image_name = "FDG";
		this.hbox4.Add(this.icon17);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon17]));
		w19.Position = 7;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.icon18 = new global::bfbbtracker.Icon();
		this.icon18.WidthRequest = 64;
		this.icon18.HeightRequest = 64;
		this.icon18.Events = ((global::Gdk.EventMask)(256));
		this.icon18.Name = "icon18";
		this.icon18.image_name = "SBD";
		this.hbox4.Add(this.icon18);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.icon18]));
		w20.Position = 8;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Runner 2");
		this.vbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label6]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 596;
		this.DefaultHeight = 198;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
